#!/bin/python
import sys
n=1
global reci
reci=""
argc=len(sys.argv)
while n != argc:
    if sys.argv[n] == '-r':
        reci+= " --recipient" + " "  + sys.argv[n+1]
        nu=2
    else:
        nu=1
    n=n+nu

n=1

while n != argc:
    if sys.argv[n] != '-r':
        print("\"" + reci + "\" \"" + sys.argv[n] + "\"")
        nu=1
    else:
        nu=2

    n=n+nu
