.TH add-comm 1 "Free software is cool" "" "General Commands"
.SH NAME
add-comm \- Add commands
.SH SYNOPSIS
.B add-comm
.I COMMAND
.SH DESCRIPTION
.B add-comm
is a fast way to add commands to /usr/bin/ with all permissions
.SH FILES
.TP 10
.I ~/added-comm
Contents a copy of all comands created by
.B add-comm
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
