.TH ahi 1 "Free software is cool" "" "Internet Commands"
.SH NAME
ahi \- Wait for internet
.SH SYNTAX
.B ahi
[-h] [COMMANDS]
.SH DESCRIPTION
.B ahi
is a command for wait to a server response
.PP
.B ahi
checks internet by pings to google.com
.PP
.B ahi
is util when combine with other commands
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
