.TH ahi2.beta 1 "Free software is cool" "" "Internet Commands"
.SH NAME
ahi2.beta \- Wait for internet
.SH SYNTAX
.B ahi
.I HOST
.SH DESCRIPTION
.B ahi2.beta
is a command for wait to a server response
.PP
.B ahi
checks internet by pings to http://\fIHOST
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
