.TH bep 1 "Free software is cool" "" "Utilities Commands"
.SH NAME
ahi \- beep when finish the command
.SH SYNOPSIS
.B bep
COMMAND
.SH DESCRIPTION
.PP
.B bep
indicate with beep when finish the command
.PP
.B bep
makes a 1 kHz sound if command success or 200 kHz sound if command fails
.PP
.PP
Error code is same as executed command
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
