.TH bepmuc 1 "Free software is cool" "" "Utilities Commands"
.SH NAME
bepmuc \- Beep music command tool
.SH DESCRIPTION
.B bepmuc
is a tool to make music in pc\-speaker
.PP This tool uses
.I beep
.SH SYNOPSIS
.B bepmuc
.I OPTIONS
.SH OPTIONS
You need to write the musical notes in Spanish
.PP
add
.B a
to sharp note. Example: \"doa rea\"
.PP
Default duration is duration of eighth note
.PP
Use
.B s
to Sixteenth duration, use
.B n
to Quarter duration, and
.B b
for half duration
.PP
Use
.B w
to add space if you want add
.B beep
commands
.SH EXAMPLE
.B bepmuc
doa sol rea sis sols mi dow-Dw500 soln min dob
.SH SEE ALSO
.I beep(1)
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
