.TH chrometemp 1 "Free software is cool" "" "Internet Commands"
.SH NAME
chrometemp \- Temporal chrome
.SH DESCRIPTION
.B chrometemp
starts a chrome instance in temp folder
.SH SYNTAX
.B chrometemp
.I OPTIONS
.SH OPTIONS
.B --clean
.PP
Remove all chrometemp folders of /tmp/
.PP
.B
NAME
.PP
Open specific chromentmp dir
.PP
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
