.TH cner 1 "Free software is cool" "" "Utility Commands"
.SH NAME
clip \- Cnee record and play
.SH DESCRIPTION
.B clip
is a command for record and play mouse records using
.B cnee
.SH OPTIONS
.TP
.PD
.TP
.B \-r
Records mouse
.PP
.TP
.B -p
Play mouse record
.PP
.TP
.B -k
Kill all cnee processes
.SH FILES
~/events.xnr
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>

