.TH demf 1 "Free software is cool" "" "General Commands"
.SH NAME
demf \- Deletes all empty folders
.SH BETA
.TP
.B Warning! BETA
This command is under beta and may
.B delete important files or folders
.PP
.B PLEASE CAUTION
.SH DESCRIPTION
.B demf
can delete all empty files or folders in a dir
.SH SYNOPSIS
.TP 10
.B demf
Deletes all empty files
.PP
.TP
.B demf --folder
Deletes all empty folders
.SH SIMILAR
For folders you can use
.B rmdir *
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
