.TH dplt 1 "Free software is cool" "" "Packages Commands"
.SH NAME
dplt \- Debian Compile Tool
.SH SYNOPSIS
.TP
.B dplt\fR\ SOURCE\ [GPG_KEY_ID]

The SOURCE folder need be in format (name\-version)
.SH DESCRIPTION
.B dplt
is a easy tool to compile source to debian installer.
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com
