.TH exparg 1 "Free software is cool" "" "Utitilies Commands"
.SH NAME
exparg \- Automatically input text to interactive command
.SH SYNOPSIS
.B exparg
.BI \fIEXPECTED\ RESPONSE\ \fB[\fIEXPECTED\ RESPONSE\fB\...]\ \fICOMMAND
.SH DESCRIPTION
.B expagr
executes a command, wait for a expected text, and send response
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
