.TH gesynfo 1 "Free software is cool" "" "Utilities Commands"
.SH NAME
gesynfo \- Get system info
.SH DESCRIPTION
.B gesynfo
is a utilitie command to get different system information
.SH SYNOPSIS
.B gesynfo
.I OPTIONS
.SH OPTIONS
.TP 10
.B dispres
Get actual screen resolution
.TP
.B ip
Get current ip(s)
.TP
.B useof
.RS
.B ram
.RS 5
Get ram usage
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>

