.TH note 1 "Free software is cool" "" "Packages Commands"
.SH NAME
note \- Manage notes from command line
.SH SYNOPSIS
.TP
.B note
Create a note
.TP
.B note [-r]
Read note
.SH DESCRIPTION
.B note
Is a tool to create notes from command-line
.PP
Automatically escape characters
.B (exept backslash "\")
, don't worry if appears error
.PP
The bash version is
.B note.sh
.SH FILES
.I ~/.notes.db
.RS 10
.B note
Database
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
