.TH nsmap 1 "Free software is cool" "" "Packages Commands"
.SH NAME
nsmap \- Search devices in lan
.SH SYNOPSIS
.B nsmap
[SUBNET]
.SH DESCRIPTION
.B note
is a tool search info of devices in lan
.PP
This tool show more devices than
.B nmap
, but less info
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
