.TH nxc 1 "Free software is cool" "" "Utils Commands"
.SH NAME
nxc \- Manage clipboard
.SH DESCRIPTION
.B nxc
saves and restores clipboard
.SH SYNOPSIS
.PP
.TP
.B "\-s(et)"
save clipboard to database with name specifed in yad
.TP
.B "\-r(ead)"
copy to clipboard text saved with name specifed in yad
.SH FILES
~/.notes.db
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
