.TH pdel 1 "Free software is cool" "" "Files Commands"
.SH NAME
pch \- Permanent delete file
.SH SYNOPSIS
.B pdel
FILE
.SH DESCRIPTION
.B "Use the program carefully. The archive can be recuperated"
.PP
.B pdel
deletes and overwrites a file, to make totally inaccesible
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
