.TH ruleta-rusa 1 "Free software is cool" "" "Funny Commands"
.SH NAME
ruleta-rusa \- Rusian roulette
.SH DESCRIPTION
Russian roulette. Tells if live or dead.
.SH EXIT STATUS
If you alive the exit status is
.B 0
.PP
If you dead then the exit code is
.B 1
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
