.TH tosy 1 "Free software is cool" "" "Files Commands"
.SH NAME
tosy \- Manage symlinks
.SH DESCRIPTION
.B tosy
converts symlinks to normal files
.SH SYNOPSIS
.B tosy
[-r]
.BI { FILE | "" --all "" }
.SH OPTIONS
.TP
.B "\-r"
Convert
.I .tosy
file to symlink
.TP
.B "\-\-all"
Selects all
.I .tosy
files or symlinks
.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
