.TH work 1 "Free software is cool" "" "Work Commands"
.SH NAME
work \- Homework database
.SH DESCRIPTION
.B work
is a command-line tool to manage homework
.SH SYNOPSIS
.B work
.BI [ OPTIONS ]
.SH OPTIONS
.TP 10
.B work
Read all works
.TP 10
.BI work " " "add " TITLE " " CONTENT
Add a homework to database
.TP 10
.BI work " " del " TITLE " [ CONTENT ]
.P
Ohh, too lazy to update this obsolete manual page. Sorry xd

.SH AUTHOR(S)
.B Ike Darien Nweke <erenburg68@gmail.com>
