#!/bin/bash
#noman
#ls -1 --escape $(echo "$args" | awk '!/^ *-/') |
set -x
ls $@ |
while read file; do
	fileout=$(gpg -v --use-embedded-filename $file 2>&1 | awk '/gpg: original file name/' | cut -d'=' -f2)
	ln -s $(s=${fileout%\'};echo ${s#\'}) ${file}dec
#	ln -s ${file%.gpg} file
#	$(echo "$args" | awk '/^ *-/') "$file";
done
