#!/bin/bash
path=/var/tmp/.chrometemp
mkdir -p $path
args="$1"
if [ "$args" == "--clean" ]; then
	rm -R $path*
else
	if [ -z "$args" ]; then
		n=$(expr $(dir $path | awk '/chrometmp/' | wc -l) + 1)
	else
		n="$args"
	fi
	google-chrome --user-data-dir=$path$n
fi
