#!/bin/bash
if [ "$1" == "-r" ]; then
	cnee --record -o ~/events.xnr --mouse
fi

if [ "$1" == "-p" ]; then
	cnee --replay -f ~/events.xnr
fi

if [ "$1" == "-k" ]; then
	kill -9 $(pidof cnee)
fi

if [ -z "$1" ]; then
echo Use arguments
fi
