#!/bin/bash
#noman
a="$@"
	while IFS= read -r line; do
		if [[ "$line" == file:///* ]]; then 
			ln -s $(echo "$line" | sed 's/file:\/\///g') .
		else
			wget -nc $line;
		fi
	done < <(ned -l $(ned $a))
