#!/bin/bash
#noman
dir="$(realpath /home/d134020a18/.ned)"
mkdir -p "$dir/$1.d"
cd "$dir/$1.d"
cat "$dir/$1.ned" |
	while read pack; do
		if [[ "$pack" =~ file:///.* ]]; then 
			ln $(echo "$pack" | sed 's/file:\/\///g') .
		else
			wget $pack;
		fi
	done
