#!/bin/bash -i

#Get display resolution
gesynfo_dispres() {
	xdpyinfo |
	grep dimensions |
	sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/' 
}

#Get ip/s
gesynfo_ip() {
	i=$(ls -1 /sys/class/net | grep -vx lo);
	[ -z "$1" ] || i=$1
	echo "$i" |
	while read a; do
		getip $a;
	done
}

#Get gateway ip
gesynfo_apip() {
eval $(echo "awk '/default/&&/$1/&&/via/{print \$3}' <(ip r)")
}

#Get the interface of a ip
#gesynfo_ifofip() {
#Soon...
#}

#Get user and pid of a pts
gesynfo_ptsinfo() {
	ps -A -o user:20,pid,tty,command |
	grep -e [p]ts/"$(echo $1 | cut -d'/' -f2)" | grep -e '-[b]ash' |
	awk '{print $1,$2,$3}'
}

#Get active ssh sessions
gesynfo_sshsessions() {
	out=$(
	who |
	awk '/pts\// {print $2}' |
	while read pts; do
		gesynfo_ptsinfo $pts
	done)
	if [ -z "$out" ]; then
		(echo No ssh connections; exit 1)
	else
		echo "$out"
	fi
}

#Get mouse position
#Requires xdotool
gesynfo_mousexy() {
	xd getmouselocation --shell |
	head -n 2 |
	cut -d'=' -f2 |
	tr '\n' '\ '
}

#Start
printf $@ | awk '{$1=""; print $0}' | gesynfo_$@ $(tee)
