#!/bin/bash -i
gesynfo_dispres() {
	xdpyinfo |
	grep dimensions |
	sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/' 
}

gesynfo_ip() {
	i=$(ls -1 /sys/class/net);
	[ -z "$1" ] || i=$1
	echo "$i" |
	while read a; do
		getip $a;
	done
}

gesynfo_apip() {
eval $(echo "awk '/default/&&/$1/&&/via/{print \$3}' <(ip r)")
}

gesynfo_ifofip() {
echo Soon...
}

gesynfo_ptsinfo() {
	ps -A -o user:20,pid,tty,command |
	grep -e [p]ts/"$(echo $1 | cut -d'/' -f2)" | grep -e '-[b]ash' |
	awk '{print $1,$2,$3}'
}

gesynfo_sshsessions() {
	out=$(
	who |
	awk '/pts\// {print $2}' |
	while read pts; do
		gesynfo_ptsinfo $pts
	done)
	if [ -z "$out" ]; then
		(echo No ssh connections; exit 1)
	else
		echo "$out"
	fi
}

gesynfo_mousexy() {
	xd getmouselocation --shell |
	head -n 2 |
	cut -d'=' -f2 |
	tr '\n' '\ '
}

printf $@ | awk '{$1=""; print $0}' | gesynfo_$@ $(tee)
