#!/bin/python
import sys
import subprocess
import os
from glob import glob
n=1
global reci
reci=""
argc=len(sys.argv)
while n != argc:
    if sys.argv[n] == '-r':
        reci+= " --recipient" + " "  + sys.argv[n+1]
        nu=2
    else:
        nu=1
    n=n+nu

n=1

while n != argc:
    if sys.argv[n] != '-r':
        subprocess.check_call(['/bin/gpgu.dep', reci, sys.argv[n]])
#        print("gpgu " + "\"" + reci + "\" \"" + sys.argv[n] + "\"")
        nu=1
    else:
        nu=2

    n=n+nu
