#!/bin/bash
#java -jar
main() {
	java -jar $@
}
if [ -f "${#}" ]; then
	main "${!#}";
elif (whereis "${!#}"); then
	main $(ls -1 $(whereis ${!#}|cut -d ':' -f2) | awk /${!#}$/);
else
	echo Not found;
fi;
