#!/bin/bash
#noman
set -x

log() {
	[ "$last" != "$1" ] &&
	echo $(date): $2 >> ~/necha
	last="$1"
}

while sleep 2; do
	if (ping -W 1 -c 1 google.com); then
		log 0 "Connected succefully"
		echo yes;
	else
		log 1 "Error: Connection Failed"
		while true; do
			(beep -f 100 -D 1000 -n -f 1000 -D 1000);
		done&
		pid=$!
		trap "kill $pid; echo Terminating...; exit" SIGINT
		ahi #-h 192.168.0.1
		kill $pid
		log 0 "Reconnected succefully"
	fi;
done;
