#!/bin/bash
#noman
set -x;

server="$1"

log() {
	[ "$last" != "$1" ] &&
	echo $(date): $2 >> ~/necha;
	last="$1";
}

while sleep 2; do
	if (ping -W 1 -c 1 ${server:=google.com}); then
		log 0 "Connected succefully";
	else
		log 1 "Error: Connection Failed";
		while true; do
			(beep -f 100 -D 1000 -n -f 1000 -D 1000);
		done&
		pid=$!;
		trap "kill $pid; echo Terminating...; exit" SIGINT;
		ahi -h ${server:=google.com};
		kill $pid;
		log 0 "Reconnected succefully";
#		bepmuc -f internet;
	fi;
done;
