#!/bin/bash



[ "$1" == "read" ] && { 
cat ~/.notes.db | grep "$2\#" | sed -e "s/$2#//"; }




[ "$1" == "edit" ] {
	echo Write the note:
	for (( ; ; )); do
		read note;
		if [ $note == breaknote ]; then
			break;
		else
			echo $1\#$note >> ~/.notes.db
		fi;
	done
}

