#!/bin/bash

# If arguments
if ! [ -z "$@" ]; then

	# If argument is "-h" or "--help"
	if [ "$@" == -h ] || [ "$@" == "--help" ]; then echo Usage: nsmap \[Subnet mask\]; exit; fi
else

	# ip is not specified
	specified_ip=0
fi


if [ -z "$specified_ip" ]; then

	# Set ip
	ip=$(echo $1);
else

	# Get ip (only support prefix 24)
	ip=$(gesynfo ip);
fi

# Too lazy to continue
sub=$(echo $ip | cut -d'.' -f '1,2,3')
if [ -z "$sub" ]; then
	echo No ip adresses found
	exit
fi
for i in {0..255}; do
	echo -n $sub.$i\ > /tmp/ns
	if nslookup $sub.$i >> /tmp/ns; then
		cat /tmp/ns | awk '{$2=""; print $0}'
	fi;
done
