#!/bin/bash
mkdir -p "~/screenshots"
date=$(date +"%Y-%m-%d_%R:%S");
[ -f ~/screenshots/${date}.jpg ] &&
{ 
  a=_;
  while [ -f ~/screenshots/${date}_$n.jpg ]; do
    n=$(($n+1));
  done; 
};
xfce4-screenshooter --save ~/screenshots/$date$a$n.jpg -m -f
