#!/bin/bash

# If no arguments
if [ -z "$1" ]; then
	echo Arguments required

# If argument "-b", then make symlink to command
elif [ "$1" == "-b" ]; then
	w=$(which $2)
        sudo ln -s "$w" "/usr/bin/$3"
        ln -s "$w" "~/added-comm/syfiles/$3"

else
	# If no option argumants detected, then create normal symlink
	ln -s "$(realpath $1)" "$(realpath $2)"
fi
