#!/bin/bash
#Author IkeDarien
#Compiles bash script to deb
echo "This script have errors and is not finished, that's why not executes"
exit
function va {
	echo Version:
	read v; v1=$(echo "$v" | tr -dc '[:digit:]')
	if [ -z "$v1" ]; then va; fi
}
if [ ! -f $@ ]; then echo Executable not found; kill $$; fi
va
c=$@-$v
mkdir $c
cp $@ $c/
cd $c
if ! dh_make --indep --createorig; then
	echo error; kill -9 $$;
fi
nano debian/control
grep -v makefile debian/rules > debian/rules.new
mv debian/rules.new debian/rules
echo "$@" usr/bin > debian/install
echo "$v" > debian/source/format
rm debian/*.ex
debuild -us -uc
cd ..
rm -rf "$c"
