#!/bin/bash
#Beta
pnrp=$(realpath ~/pnrp)
if [ ! -f "$pnrp" ] || ([ ! -z "$@" ] && [ "$@" == "--replace" ]); then
	pnrpdep2 > /tmp/pnrp2
	pnrpdep > /tmp/pnrp1
	cat /tmp/pnrp1 | uniq > /tmp/pnrp
	rm /tmp/pnrp1
	comm --nocheck-order -23 /tmp/pnrp2 /tmp/pnrp > ~/pnrp
fi
	cat "$pnrp"

